In [2]:
#_Creating a matrix with output columns based on input vector(N):
#_Note1_Vandermonde matrix. If increasing is False, the first column is x^(N-1), the second x^(N-2) and so forth.
#_Note2_If increasing is True, the columns are x^0, x^1, ..., x^(N-1).
#_Order of the powers of the columns.If True,the powers increase from left to right,if False (the default) they are reversed.
#_x-array_like_1-D input array.
#_N Number of columns in the output. If N is not specified, a square array is returned (N = len(x)).

import numpy as np
x=np.array([1,2,3,4])
N=3
np.vander(x,N)     #Generate a vandermode matrix function using np.vander from Numpy API reference .

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

In [3]:
#_Apply the condition and logic Vandermode matrix:
np.column_stack([x**(N-1-y) for y in range (N)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]], dtype=int32)

In [4]:
x=np.array([1,2,3,4])
np.vander(x,increasing=False)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [5]:
#_Find the Determinant of a square vandermodematrix is the product of the difference between the valueof the input vector:
np.linalg.det(np.vander(x))

12.00000000000001

In [6]:
# ""The moving_average function in an array,n-th over window where size=3 in a given sequence defined as n=3.
#  where_cumulative sum of array element given over a matrix_func_defined_numpy.cumsum(arr,axis=None,dtype=None,out=None).
#   arr:Array_containing numbers whose cumulative sum is desired & Axis along which the cumulative sum is computed.""
import numpy as np
def moving_average(test,n=3):
    value=np.cumsum(test,dtype=None)
    value[n:]=value[n:]-value[:-n]
    return value[n - 1:] / n
test=[3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
print(moving_average(test,n=3))

[  5.           4.66666667   5.66666667   6.66666667   9.66666667
  28.66666667  49.33333333  72.66666667  84.          93.33333333
 116.33333333]
