In [146]:
import numpy as np
fr=np.array(['vbhvh',2,3])
print(fr)

['vbhvh' '2' '3']


In [147]:
type(fr)

numpy.ndarray

In [148]:
#_upcasting/two dim:-
fr1=np.array([1, 2, 3.0])
fr2=np.array([[1,2],[3,4]])
print(fr1)

[1. 2. 3.]


In [149]:
print(fr2)

[[1 2]
 [3 4]]


In [150]:
#_minimum two_dimension_AS per Requirement Similarly_Create Dimension:-
np.array([1,2,3],ndmin=5)

array([[[[[1, 2, 3]]]]])

In [151]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [152]:
#Data_Type Consisting more than one element:-
x=np.array([(1,2),(3,4)],dtype=[('a','i2'),('b','<i8')])
x

array([(1, 2), (3, 4)], dtype=[('a', '<i2'), ('b', '<i8')])

In [153]:
type(x[1][0])

numpy.int16

In [154]:
type(x[1][1])

numpy.int64

In [155]:
#_create_an array from sub-classes:-
np.mat(np.array([[1,2],[3,4]]))

matrix([[1, 2],
        [3, 4]])

In [156]:
np.mat('1 2;3 4')

matrix([[1, 2],
        [3, 4]])

In [157]:
#_numpy_as_array:
#_Convert-the input to an array
#_Convert-the list into an array
a=[1,2]
print(type(a))
print(type(np.asarray(a)))

<class 'list'>
<class 'numpy.ndarray'>


In [158]:
# Existing array's are not Copied:
a=np.array([1,2])
type(a)

numpy.ndarray

In [159]:
np.asarray((1,2))

array([1, 2])

In [160]:
# if dtype is set,array is copied only if dtype doesnot match:
a=np.array([1,2],dtype=np.float32)
a

array([1., 2.], dtype=float32)

In [161]:
np.asarray([1,2]) is a

False

In [162]:
np.asarray([1,2])

array([1, 2])

In [163]:
np.asarray(a,dtype=np.float64) is a

False

In [164]:
#ndarray subclasses are not passed through


In [165]:
issubclass(np.matrix,np.ndarray)

True

In [166]:
a=np.matrix([[1,2]])
np.asanyarray(a)

matrix([[1, 2]])

In [167]:
np.asarray(a) is a

False

In [168]:
np.asanyarray(a)is a

True

In [169]:
#numpy.asanyarray
a=[1,2]
np.asanyarray(a)

array([1, 2])

In [170]:
#numpy_copy
np.array(a,copy=True)

array([1, 2])

In [171]:
#create an array x ,with a reference y and a copy z_clone_:
x=np.array([1,2,3])
x

array([1, 2, 3])

In [172]:
#_clone_the_x and copy():
y=x

In [173]:
z=np.copy(x)

In [174]:
y[0]=100
x

array([100,   2,   3])

In [175]:
id(x[0])

549859416560

In [176]:
id(y[0])

549859416592

In [177]:
#_numpy_form_function:
np.fromfunction(lambda i,j:i==j,(3,3),dtype=int)

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [178]:
#Create a new 1-d array from iterable object.
iterable=(x*x for x in range(5))
iterable

<generator object <genexpr> at 0x00000080062E1200>

In [179]:
np.fromiter(iterable,float)

array([ 0.,  1.,  4.,  9., 16.])

In [180]:
#_A_new 1-D array initaialized from text data in a string:
np.fromstring('1,2',dtype=int,sep=',')

array([1, 2])

In [181]:
np.fromstring('234 234',dtype=int,sep=',')

array([234])

In [182]:
# How to Create a record array from a flat list of array's_numpy.ndarray
x1=np.array([1,2,3,4])
x2=np.array(['a','dd','xyz','12'])
x3=np.array([1.1,2,3,4])
x4=np.array([1.1,2,3,4])
type(x4)

numpy.ndarray

In [183]:
#np_core_records_fromarrays:
r=np.core.records.fromarrays([x1,x2,x3,x4],names='a,b,c,d')
r

rec.array([(1, 'a', 1.1, 1.1), (2, 'dd', 2. , 2. ), (3, 'xyz', 3. , 3. ),
           (4, '12', 4. , 4. )],
          dtype=[('a', '<i4'), ('b', '<U3'), ('c', '<f8'), ('d', '<f8')])

In [184]:
print(r[1]["a"])

2


In [185]:
x1[1]=34

In [186]:
x1[1]

34

In [187]:
#_Data_type:-
my_list=[1,2,3]
import numpy as np
arr=np.array(my_list)
print("Type/Class of this object:",type(arr))
print("Here is the vector\n------\n",arr)

Type/Class of this object: <class 'numpy.ndarray'>
Here is the vector
------
 [1 2 3]


In [188]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]
mat = np.array(my_mat)
print("Type/Class of this object:",type(mat))
print("Here is the matrix\n----------\n",mat,"\n----------")
print("Dimension of this matrix: ",mat.ndim,sep='') #ndim gives the dimensison, 2 for a matrix, 1 for a vector
print("Size of this matrix: ", mat.size,sep='') #size gives the total number of elements
print("Shape of this matrix: ", mat.shape,sep='') #shape gives the number of elements along each axes (dimension)
print("Data type of this matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array

Type/Class of this object: <class 'numpy.ndarray'>
Here is the matrix
----------
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
----------
Dimension of this matrix: 2
Size of this matrix: 9
Shape of this matrix: (3, 3)
Data type of this matrix: int32


In [189]:
my_mat = [[1.1,2,3],[4,5.2,6],[7,8.3,9]]
mat = np.array(my_mat)
print("Data type of the modified matrix: ", mat.dtype,sep='') #dtype gives the data type contained in the array
print("\n\nEven tuples can be converted to ndarrays...")

Data type of the modified matrix: float64


Even tuples can be converted to ndarrays...


In [190]:
b = np.array([(1.5,2,3), (4,5,6)])
print("We write b = np.array([(1.5,2,3), (4,5,6)])")
print("Matrix made from tuples, not lists\n---------------------------------------")
print(b)

We write b = np.array([(1.5,2,3), (4,5,6)])
Matrix made from tuples, not lists
---------------------------------------
[[1.5 2.  3. ]
 [4.  5.  6. ]]


In [191]:
print("A series of numbers:",type(np.arange(5,16)))
np.arange(5,16,2.3)# A series of numbers from low to high

A series of numbers: <class 'numpy.ndarray'>


array([ 5. ,  7.3,  9.6, 11.9, 14.2])

In [192]:
list(range(5,16,2))

[5, 7, 9, 11, 13, 15]

In [193]:
list(range(50,-1,5))

[]

In [194]:
print("Numbers spaced apart by 2:",np.arange(50,-1,5)) # Numbers spaced apart by 2

Numbers spaced apart by 2: []


In [195]:
print("Numbers spaced apart by float:",np.arange(0,11,2.5)) # Numbers spaced apart by 2.5

Numbers spaced apart by float: [ 0.   2.5  5.   7.5 10. ]


In [196]:
print("21 linearly spaced numbers between 1 and 5\n--------------------------------------------")
print((np.linspace(1,5,50)))

21 linearly spaced numbers between 1 and 5
--------------------------------------------
[1.         1.08163265 1.16326531 1.24489796 1.32653061 1.40816327
 1.48979592 1.57142857 1.65306122 1.73469388 1.81632653 1.89795918
 1.97959184 2.06122449 2.14285714 2.2244898  2.30612245 2.3877551
 2.46938776 2.55102041 2.63265306 2.71428571 2.79591837 2.87755102
 2.95918367 3.04081633 3.12244898 3.20408163 3.28571429 3.36734694
 3.44897959 3.53061224 3.6122449  3.69387755 3.7755102  3.85714286
 3.93877551 4.02040816 4.10204082 4.18367347 4.26530612 4.34693878
 4.42857143 4.51020408 4.59183673 4.67346939 4.75510204 4.83673469
 4.91836735 5.        ]


In [197]:
#_Matrix Craetion:
print("Vector of zeroes\n---------------------")
print(np.zeros(5))

Vector of zeroes
---------------------
[0. 0. 0. 0. 0.]


In [198]:
print("Matrix of zeroes\n--------------------")
print(np.zeros((3,4))) # Notice Tuples

Matrix of zeroes
--------------------
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [199]:
print("Vector of ones\n---------------------")
print(np.ones(5))

Vector of ones
---------------------
[1. 1. 1. 1. 1.]


In [200]:
print("Matrix of ones\n---------------------")
print(np.ones((5,2,8))) # Note matrix dimension specified by Tuples


Matrix of ones
---------------------
[[[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1. 1. 1. 1.]]]


In [201]:
print("Matrix of 5's\n---------------------")
print(5+np.ones((3,5)))

Matrix of 5's
---------------------
[[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [202]:
print("Empty matrix\n-------------\n", np.empty((3,5)))

Empty matrix
-------------
 [[6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]
 [6. 6. 6. 6. 6.]]


In [203]:
mat1 = np.eye(4) 
print("Identity matrix of dimension", mat1.shape)
print(mat1)

Identity matrix of dimension (4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [204]:
np.arange(3)

array([0, 1, 2])

In [205]:
np.arange(3.0)

array([0., 1., 2.])

In [206]:
 np.arange(3,7)

array([3, 4, 5, 6])

In [207]:
np.arange(3,7,2)

array([3, 5])

In [208]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [209]:
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [210]:
np.linspace(2.0, 3.0, num=9, retstep=True)

(array([2.   , 2.125, 2.25 , 2.375, 2.5  , 2.625, 2.75 , 2.875, 3.   ]), 0.125)

In [211]:
#_Return number spaced evenly a log scale
#_num_depend on number_5
np.linspace(2.0,3.0,num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [212]:
np.logspace(2.0,3.0,num=4,base=10)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [213]:
np.logspace(2.0,3.0,num=4,base=2.0)

array([4.        , 5.0396842 , 6.34960421, 8.        ])

In [214]:
#_Extract a diagonal or construct a diagonal array:
x=np.arange(16).reshape((-1,4))
x

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [215]:
np.diag(x)

array([ 0,  5, 10, 15])

In [216]:
np.diag(x,k=2)

array([2, 7])

In [217]:
np.diag(x,k=-1)

array([ 4,  9, 14])

In [218]:
np.diag(np.diag(x))

array([[ 0,  0,  0,  0],
       [ 0,  5,  0,  0],
       [ 0,  0, 10,  0],
       [ 0,  0,  0, 15]])

In [219]:
#_create a tw dimensional array with flattened input as a diagonal:
np.diagflat([[1,2],[3,4]])

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [220]:
np.diagflat(([1,2],1))

array([[list([1, 2]), 0],
       [0, 1]], dtype=object)

In [221]:
np.diagflat([1,2],1)

array([[0, 1, 0],
       [0, 0, 2],
       [0, 0, 0]])

In [222]:
#_An array with ones at and below the given diagonal and zeros elsewhere.
np.tri(3,5,1,dtype=int)

array([[1, 1, 0, 0, 0],
       [1, 1, 1, 0, 0],
       [1, 1, 1, 1, 0]])

In [223]:
np.tri(3,5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [224]:
#_Return upper triangle of an array:
np.triu([[1,2,3],[4,5,6],[7,8,9],[10,11,12]],1)

array([[0, 2, 3],
       [0, 0, 6],
       [0, 0, 0],
       [0, 0, 0]])

In [225]:
#_Random number generation:
#_2 by 3 matrix with random numbers ranging from 0 to 1,_No Tuple is necessary
print("Random number generation from uniform distribution:")
print(np.random.rand(2,3))

Random number generation from uniform distribution:
[[0.30315247 0.72560355 0.04101785]
 [0.11090702 0.85231166 0.10112153]]


In [226]:
print("Number's from Normal distribution with zero mean and standard normal:")
print(np.random.randn(4,3))

Number's from Normal distribution with zero mean and standard normal:
[[-0.1844987  -0.05541022  0.67202491]
 [ 0.2191274  -1.7739182  -1.09976727]
 [-1.6230602  -1.01729439  1.59256642]
 [-0.78001291 -0.35050558  0.44049865]]


In [227]:
print(np.random.randint(1,100,(4,4))) #randint (low, high, # of samples to be drawn in a tuple to form a matrix)
print("\n20 samples drawn from a dice throw:",np.random.randint(1,7,20)) # 20 samples drawn from a dice throw

[[83 93 84 98]
 [18 52 14 94]
 [58 16  3 21]
 [80 30 11 97]]

20 samples drawn from a dice throw: [2 3 2 1 1 3 3 1 2 3 4 6 6 1 2 3 3 6 6 5]


In [228]:
#_Reshaping
from numpy.random import randint as ri
a=ri(1,100,30)
b=a.reshape(2,3,5)
c=a.reshape(6,-19878)
c

array([[ 8, 65, 11, 81, 15],
       [33, 89, 37, 18, 70],
       [69, 25, 20, 74, 51],
       [49, 21, 37, 92, 20],
       [58, 10, 85, 74, 38],
       [17, 12, 31,  4,  7]])

In [229]:
print("Shape of a:",a.shape)
print("Shape of b:",b.shape)
print("Shape of c:",c.shape)

Shape of a: (30,)
Shape of b: (2, 3, 5)
Shape of c: (6, 5)


In [230]:
print("\na looks like\n",'-'*20,"\n",a,"\n",'-'*20)
print("\nb looks like\n",'-'*20,"\n",b,"\n",'-'*20)
print("\nc looks like\n",'-'*20,"\n",c,"\n",'-'*20)


a looks like
 -------------------- 
 [ 8 65 11 81 15 33 89 37 18 70 69 25 20 74 51 49 21 37 92 20 58 10 85 74
 38 17 12 31  4  7] 
 --------------------

b looks like
 -------------------- 
 [[[ 8 65 11 81 15]
  [33 89 37 18 70]
  [69 25 20 74 51]]

 [[49 21 37 92 20]
  [58 10 85 74 38]
  [17 12 31  4  7]]] 
 --------------------

c looks like
 -------------------- 
 [[ 8 65 11 81 15]
 [33 89 37 18 70]
 [69 25 20 74 51]
 [49 21 37 92 20]
 [58 10 85 74 38]
 [17 12 31  4  7]] 
 --------------------


In [231]:
#_Vector_of_random integer's:
A=ri(1,100,10)
print("\nvector of random integers:\n",'-'*25,"\n",A)
print("\nHere is the sorted vector:\n",'-'*25,"\n",np.sort(A))


vector of random integers:
 ------------------------- 
 [68 76 21 87 75 76 80 23 28 30]

Here is the sorted vector:
 ------------------------- 
 [21 23 28 30 68 75 76 76 80 87]


In [232]:
#_Matrix of random integers:
M=ri(1,100,25).reshape(5,5)
print("\nHere is the sorted matrix along each column\n",'-'*35,"\n",np.sort(M,axis=1,kind='mergesort'))
M     


Here is the sorted matrix along each column
 ----------------------------------- 
 [[47 51 58 79 83]
 [ 1 33 34 75 97]
 [ 5 39 81 82 89]
 [ 3  3 59 62 99]
 [ 7 31 35 40 76]]


array([[58, 83, 51, 47, 79],
       [33,  1, 75, 97, 34],
       [89, 82,  5, 39, 81],
       [ 3, 99, 59,  3, 62],
       [31, 76,  7, 35, 40]])

In [233]:
print("Max of a:",M.max())
print("Max of b:",b.max())
b

Max of a: 99
Max of b: 92


array([[[ 8, 65, 11, 81, 15],
        [33, 89, 37, 18, 70],
        [69, 25, 20, 74, 51]],

       [[49, 21, 37, 92, 20],
        [58, 10, 85, 74, 38],
        [17, 12, 31,  4,  7]]])

In [234]:
M

array([[58, 83, 51, 47, 79],
       [33,  1, 75, 97, 34],
       [89, 82,  5, 39, 81],
       [ 3, 99, 59,  3, 62],
       [31, 76,  7, 35, 40]])

In [235]:
print("Max of a location:",M.argmax(axis=1))
print("Max of b location:",b.argmax())
print("Max of c location:",c.argmax())

Max of a location: [1 3 0 1 1]
Max of b location: 18
Max of c location: 18


In [236]:
#_indexing and slicing :
arr=np.arange(0,11)
print("Array:",arr)

Array: [ 0  1  2  3  4  5  6  7  8  9 10]


In [237]:
print("Element at 7th index is:",arr[7])

Element at 7th index is: 7


In [238]:
print("Element's from 3rd to 5th index are:",arr[3:6:2])

Element's from 3rd to 5th index are: [3 5]


In [239]:
print("Element's upto 4th index are",arr[:4])
arr

Element's upto 4th index are [0 1 2 3]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [240]:
print("3 Element's from last backwards are",arr[-1:-6:2])

3 Element's from last backwards are []


In [241]:
arr=np.arange(0,21,2)
print("New array:",arr)

New array: [ 0  2  4  6  8 10 12 14 16 18 20]


In [242]:
#_pass a list as a index to subset
print("Element at 2nd,4th and 9th index are:",arr[[2,4,9]])

Element at 2nd,4th and 9th index are: [ 4  8 18]


In [243]:
import numpy as np
mat=np.array(ri(10,100,15).reshape(3,5))
print("\nMatrix of random 2-digit numbers\n",mat)
mat[1:4,3:5]
mat[0:3,[1,3]]


Matrix of random 2-digit numbers
 [[59 24 89 25 57]
 [44 94 73 53 34]
 [34 25 21 89 90]]


array([[24, 25],
       [94, 53],
       [25, 89]])

In [244]:
mat[0:3,[1,3]]
mat

array([[59, 24, 89, 25, 57],
       [44, 94, 73, 53, 34],
       [34, 25, 21, 89, 90]])

In [245]:
print("\nDouble bracket indexing:\n",'-'*23,sep='')
print("Element in row index 1 and column index 2:",mat[1][1])
mat


Double bracket indexing:
-----------------------
Element in row index 1 and column index 2: 94


array([[59, 24, 89, 25, 57],
       [44, 94, 73, 53, 34],
       [34, 25, 21, 89, 90]])

In [246]:
print("\nSingle bracket with comma indexing:\n",'-'*34,sep='')
print("Element in row index 1 and column index2:",mat[1,2])


Single bracket with comma indexing:
----------------------------------
Element in row index 1 and column index2: 73


In [247]:
print("Entire row at index 2:",mat[2])
print("Entire column at index 3:",mat[:,3])

Entire row at index 2: [34 25 21 89 90]
Entire column at index 3: [25 53 89]


In [248]:
print("\nsubsetting substring matrices:\n",'-'*30,sep='')
print("Matrix with row indices 1 and 2 and column indices 3 and 4 \n",mat[1:3,3:5])


subsetting substring matrices:
------------------------------
Matrix with row indices 1 and 2 and column indices 3 and 4 
 [[53 34]
 [89 90]]


In [249]:
print("\nMatrix_with row indices 0 and 1 and column indices 1 and 3:\n:",'-'*58,sep='')
mat[0:2,[1,3]]


Matrix_with row indices 0 and 1 and column indices 1 and 3:
:----------------------------------------------------------


array([[24, 25],
       [94, 53]])

In [250]:
#_Subsetting:
mat=np.array(ri(10,100,15)).reshape(3,5)
print("\nMatrix of random 2-digit numbers\n",'-'*35,sep='')
mat>50


Matrix of random 2-digit numbers
-----------------------------------


array([[False,  True,  True,  True, False],
       [False,  True,  True, False, False],
       [False, False,  True, False,  True]])

In [251]:
print("Element greater than 50\n",mat[mat>50])

Element greater than 50
 [61 89 63 55 79 68 61]


In [252]:
#_Slicing
mat=np.array([[11,12,13],[21,22,23],[31,32,33]])
print("\nOriginal matrix:\n",'-'*15,sep='')
print(mat)


Original matrix:
---------------
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [253]:
#_Change slice matrix:
mat_slice=mat[:2,:2]
print("\nSliced matrix:\n",'-'*13,sep='')
print(mat_slice)
mat_slice[0,0]=1002
print("\nChange_Sliced matrix:\n",'-'*20,sep='')
print(mat_slice)


Sliced matrix:
-------------
[[11 12]
 [21 22]]

Change_Sliced matrix:
--------------------
[[1002   12]
 [  21   22]]


In [254]:
mat_slice[0,0]=1004
print(mat_slice)

[[1004   12]
 [  21   22]]


In [255]:
print("\n But the original matrix ?WHOA! it got changed too!")
print(mat)


 But the original matrix ?WHOA! it got changed too!
[[1004   12   13]
 [  21   22   23]
 [  31   32   33]]


In [256]:
#_Little different way to Creaye a copy of the slixed matrix:
print("\nDoing it agian little differently now..\n",'-'*28,sep='')
mat=np.array([[11,12,13],[21,22,23],[31,32,33]])
print("originaln matrix")
print(mat)


Doing it agian little differently now..
----------------------------
originaln matrix
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [257]:
#_Notice the np.array command to craete anew array not just slicing
mat_slice=np.array(mat[:2:2])
print("\nSliced matrix")
print(mat_slice)


Sliced matrix
[[11 12 13]]


In [258]:
print("\nChange the sliced matrix")
mat_slice[0,0]=1000
print(mat_slice)


Change the sliced matrix
[[1000   12   13]]


In [259]:
print("\nBut the original matrix?No change this time:")
print(mat)


But the original matrix?No change this time:
[[11 12 13]
 [21 22 23]
 [31 32 33]]


In [260]:
#_Universal Function:
mat1=np.array(ri(1,10,9).reshape(3,3))
mat2=np.array(ri(1,10,9).reshape(3,3))
print("\n1st Matrix of random single-digit number\n",mat1)
print("\n1st Matrix of random single-digit number\n",mat2)


1st Matrix of random single-digit number
 [[6 5 9]
 [1 9 1]
 [5 5 2]]

1st Matrix of random single-digit number
 [[9 5 9]
 [4 5 9]
 [6 9 2]]


In [261]:
mat1*mat2

array([[54, 25, 81],
       [ 4, 45,  9],
       [30, 45,  4]])

In [262]:
print("\n_Addition\n",mat1+mat2)
print("\n Multiplacation\n",mat1@mat2)


_Addition
 [[15 10 18]
 [ 5 14 10]
 [11 14  4]]

 Multiplacation
 [[128 136 117]
 [ 51  59  92]
 [ 77  68  94]]


In [263]:
print("\n Division\n",mat1/0)


 Division
 [[inf inf inf]
 [inf inf inf]
 [inf inf inf]]


<ipython-input-263-2173c34f7bf1>:1: RuntimeWarning: divide by zero encountered in true_divide
  print("\n Division\n",mat1/0)


In [264]:
print("\nAddition of a scaler (100)\n",100+mat1)


Addition of a scaler (100)
 [[106 105 109]
 [101 109 101]
 [105 105 102]]


In [265]:
print("\nExponential,matrix cubed here:\n",mat1**2)
print("\nExponential,sqroot using pow function:\n",pow(mat1,3))


Exponential,matrix cubed here:
 [[36 25 81]
 [ 1 81  1]
 [25 25  4]]

Exponential,sqroot using pow function:
 [[216 125 729]
 [  1 729   1]
 [125 125   8]]


In [266]:
start=np.zeros((4,4))
start=start+100
start

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.],
       [100., 100., 100., 100.]])

In [267]:
#_Create a rank 1 ndarray with 3 value:
add_rows=np.array([1,0,2,5])
print(add_rows)

[1 0 2 5]


In [268]:
#_add to each row of 'start' using broadcasting
y=start+add_rows
print(y)

[[101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]
 [101. 100. 102. 105.]]


In [269]:
#_Create_an nd array which is 4*1 to broadcast across columns
add_cols=np.array([[0,1,2,3,4]])
add_cols=add_cols.T
print(add_cols)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [270]:
#_there will just broadcast in both dimensions:
add_scaler=np.array([100])
print(start+y)

[[201. 200. 202. 205.]
 [201. 200. 202. 205.]
 [201. 200. 202. 205.]
 [201. 200. 202. 205.]]


In [271]:
#_Array Math:
mat1=np.array(ri(1,10,9).reshape(3,3))
mat2=np.array(ri(1,10,9).reshape(3,3))
print("/n1st Matrix of random single-digit number\n",mat1)
print("/n2nd Matrix of random single-digit number\n",mat2)

/n1st Matrix of random single-digit number
 [[7 6 1]
 [6 8 3]
 [7 6 4]]
/n2nd Matrix of random single-digit number
 [[6 8 8]
 [7 3 5]
 [5 1 8]]


In [272]:
print("\n sq-root of 1st matrix using np",np.sqrt(mat1))


 sq-root of 1st matrix using np [[2.64575131 2.44948974 1.        ]
 [2.44948974 2.82842712 1.73205081]
 [2.64575131 2.44948974 2.        ]]


In [273]:
print("\n Exponetial powe of 1st matrix using np\n",'-'*50,np.exp(mat1))


 Exponetial powe of 1st matrix using np
 -------------------------------------------------- [[1.09663316e+03 4.03428793e+02 2.71828183e+00]
 [4.03428793e+02 2.98095799e+03 2.00855369e+01]
 [1.09663316e+03 4.03428793e+02 5.45981500e+01]]


In [274]:
print("\n10-base logarithm on 1st matrix using np\n",'-'*50,"\n",np.log10(mat1))
print(mat1)
print(mat2)


10-base logarithm on 1st matrix using np
 -------------------------------------------------- 
 [[0.84509804 0.77815125 0.        ]
 [0.77815125 0.90308999 0.47712125]
 [0.84509804 0.77815125 0.60205999]]
[[7 6 1]
 [6 8 3]
 [7 6 4]]
[[6 8 8]
 [7 3 5]
 [5 1 8]]


In [275]:
print("\nModulo reminder using np\n",'-'*35,"\n",np.fmod(mat1,mat2))
mat1%mat2


Modulo reminder using np
 ----------------------------------- 
 [[1 6 1]
 [6 2 3]
 [2 0 4]]


array([[1, 6, 1],
       [6, 2, 3],
       [2, 0, 4]], dtype=int32)

In [276]:
print("\nCombination of function by showing exponetial decay of a sinwave\n",'-'*63)
A=np.linspace(0,12*np.pi,1001)
A


Combination of function by showing exponetial decay of a sinwave
 ---------------------------------------------------------------


array([ 0.        ,  0.03769911,  0.07539822, ..., 37.62371362,
       37.66141273, 37.69911184])

In [277]:
#_Import numpy as np:
import numpy as np

In [278]:
#_Create an array 1 zeros:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [279]:
#_Craete an array 10-ones:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [280]:
#_Create an array 10-fives:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [281]:
np.ones(5)*2

array([2., 2., 2., 2., 2.])

In [282]:
#Create an integer from 10 to 50:
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [283]:
#_Create an array of all even integer from 0 to 8:
np.arange(0,51,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50])

In [284]:
#_Create an array 3*3 matrix value ranging from 0 to 8:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [285]:
#_Create 3*3 identified matrix:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [286]:
#_use nupy to generate a random number betwwen o to 1:
np.random.rand(1)

array([0.04902384])

In [287]:
#_use numpy to genertae an array of 25 randm numbers sampled from a standard normal distribution:
np.random.randn(25)

array([-0.43194837, -3.26773903, -0.19038929, -0.94541266, -0.5643904 ,
       -1.33650856, -0.37578085,  1.90969315,  0.9328337 ,  0.24646321,
        0.01123608,  1.0526152 , -0.13994854,  0.5008018 ,  1.02536158,
       -2.370546  , -0.7425056 ,  0.36145014, -1.03850908,  1.21245152,
       -0.06692696, -0.67195157, -2.27567835, -0.35368376, -0.82800772])

In [289]:
#_Craete a foollwing matrix:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

In [290]:
#_Create an array of 20 linearly spaced points betwwen 0 and 1:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [291]:
#_Numpy index and slicing selection:
# now resulting matrices
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [292]:
mat[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [293]:
mat[3:4]

array([[16, 17, 18, 19, 20]])

In [294]:
mat[3,4]

20

In [295]:
mat[:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [297]:
mat[3:5,:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [298]:
#_get the sum of all valus in mat
mat.sum

<function ndarray.sum>

In [299]:
mat.sum()

325

In [300]:
#_get the standard deviation of the values in mat:
mat.std()

7.211102550927978

In [301]:
#_get the sum of all the columns in mat:
mat.sum(axis=0)

array([55, 60, 65, 70, 75])

In [304]:
#_min(),max(),argmax(),argmin()-min or max or index of value
mat.min()

1

In [305]:
mat.max()

25

In [306]:
mat.argmin()

0

In [307]:
mat.argmax()

24

In [309]:
import numpy as np
x = np.array([1, 2, 3, 5])
N = 3
np.vander(x, N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [310]:
np.column_stack([x**(N-1-i) for i in range(N)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]], dtype=int32)

In [311]:
x = np.array([1, 2, 3, 5])
np.vander(x)

array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [312]:
np.linalg.det(np.vander(x))

48.00000000000003

In [314]:
x=np.array([1,2,3,4])
n=2
np.vander(x,N)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

In [316]:
np.column_stack([x**(N-1-i) for i in range(N)])

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]], dtype=int32)

In [317]:
x=np.array([1,2,3,4])
np.vander(x)

array([[ 1,  1,  1,  1],
       [ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [64, 16,  4,  1]])

In [321]:
np.linalg.det(np.vander(x))

12.00000000000001